title: Polynomeer's Blog
lang: en
description: Library Blog
repository: Polynomeer/polynomeer.github.io

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

layout: default
comments: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://polynomeer.github.io/" # the base hostname & protocol for your site
