title: Polynomeer's Blog
lang: en
description: Library Blog
repository: Polynomeer/polynomeer.github.io

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

layout: default
comments: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://polynomeer.github.io/" # the base hostname & protocol for your site

scss: |
  .header {
    color: #fff;
    background: #3b5998;
  }

  .header input {
    border-color: #2f477a;
  }

  .header input {
    border-radius: 10px;
    border: 1px solid #2f477a;
    font-size: 80%;
  }

  .toctree .caption {
      color: #6c89c6;
      font-weight: 600;
      line-height: 32px;
  }
  